# This script identifies anomalous OCT feature rows using MAD-based robust z-scores and IQR-based outlier counts, then ranks scans by outlier burden and exports an anomaly report for quality control. #

import os
import numpy as np
import pandas as pd


# ============================================================
# Configuration
# ============================================================

# Path to the folder containing the extracted feature spreadsheet
OUT_DIR = "path/to/file"

# Input feature file generated by the ETDRS extraction step
INPUT_FILE = os.path.join(OUT_DIR, "volume_level_features_90cols.xlsx")

# Output anomaly report
OUTPUT_FILE = os.path.join(OUT_DIR, "volume_anomaly_report_mad_and_iqr.xlsx")

# Threshold for robust z-score flagging
MAD_Z_THRESHOLD = 3.5

# Minimum number of non-missing values required to compute IQR bounds
MIN_SAMPLES_FOR_IQR = 10

# Threshold used to highlight scans with high outlier burden
FEATURE_FLAG_COUNT_THRESHOLD = 10


# ============================================================
# Helper functions
# ============================================================

def robust_z_scores(values: np.ndarray) -> np.ndarray:
    """
    Computes MAD-based robust z-scores for a 1D array.
    Returns zeros if the MAD is undefined or effectively zero.
    """
    median = np.nanmedian(values)
    mad = np.nanmedian(np.abs(values - median))

    if (not np.isfinite(mad)) or mad < 1e-12:
        return np.zeros_like(values, dtype=float)

    return 0.6745 * (values - median) / mad


def identify_feature_columns(df: pd.DataFrame) -> list[str]:
    """
    Returns the feature columns by excluding non-feature metadata columns.
    """
    non_feature_cols = {"scan_id", "volume", "eye", "flipped"}
    return [col for col in df.columns if col not in non_feature_cols]


# ============================================================
# Main anomaly detection pipeline
# ============================================================

def main():
    df = pd.read_excel(INPUT_FILE, sheet_name="formatted_90cols")
    print("Loaded rows:", len(df))

    feature_cols = identify_feature_columns(df)
    feature_matrix = df[feature_cols].astype(float)

    # --------------------------------------------------------
    # 1. MAD-based anomaly counts
    # --------------------------------------------------------
    z_score_df = pd.DataFrame(index=df.index, columns=feature_cols, dtype=float)

    for col in feature_cols:
        z_score_df[col] = robust_z_scores(feature_matrix[col].values)

    df["mad_anomaly_feature_count"] = (np.abs(z_score_df) > MAD_Z_THRESHOLD).sum(axis=1)
    df["mad_mean_abs_zscore"] = np.nanmean(np.abs(z_score_df.values), axis=1)

    # --------------------------------------------------------
    # 2. IQR-based outlier counts
    # --------------------------------------------------------
    iqr_outlier_matrix = pd.DataFrame(False, index=df.index, columns=feature_cols)

    for col in feature_cols:
        series = feature_matrix[col]
        series_non_missing = series.dropna()

        if len(series_non_missing) < MIN_SAMPLES_FOR_IQR:
            continue

        q1 = series_non_missing.quantile(0.25)
        q3 = series_non_missing.quantile(0.75)
        iqr = q3 - q1

        if (not np.isfinite(iqr)) or iqr <= 0:
            continue

        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        iqr_outlier_matrix[col] = (series < lower_bound) | (series > upper_bound)

    df["iqr_outlier_feature_count"] = iqr_outlier_matrix.sum(axis=1).astype(int)

    # --------------------------------------------------------
    # 3. Rank scans by anomaly burden
    # --------------------------------------------------------
    ranked_df = df.sort_values(
        by=[
            "mad_anomaly_feature_count",
            "iqr_outlier_feature_count",
            "mad_mean_abs_zscore",
        ],
        ascending=False,
    )

    print("\nTop 15 most anomalous scans:\n")
    print(
        ranked_df[
            [
                "scan_id",
                "volume",
                "eye",
                "mad_anomaly_feature_count",
                "iqr_outlier_feature_count",
                "mad_mean_abs_zscore",
            ]
        ].head(15)
    )

    # --------------------------------------------------------
    # 4. Highlight scans with high outlier burden
    # --------------------------------------------------------
    flagged_df = df[
        (df["mad_anomaly_feature_count"] >= FEATURE_FLAG_COUNT_THRESHOLD)
        | (df["iqr_outlier_feature_count"] >= FEATURE_FLAG_COUNT_THRESHOLD)
    ].copy()

    flagged_df = flagged_df.sort_values(
        by=[
            "mad_anomaly_feature_count",
            "iqr_outlier_feature_count",
            "mad_mean_abs_zscore",
        ],
        ascending=False,
    )

    print(
        f"\nScans with high outlier burden "
        f"(>= {FEATURE_FLAG_COUNT_THRESHOLD} flagged features by either method):"
    )
    print(
        flagged_df[
            [
                "scan_id",
                "volume",
                "eye",
                "mad_anomaly_feature_count",
                "iqr_outlier_feature_count",
                "mad_mean_abs_zscore",
            ]
        ].head(25)
    )

    # --------------------------------------------------------
    # 5. Save anomaly report
    # --------------------------------------------------------
    with pd.ExcelWriter(OUTPUT_FILE, engine="openpyxl") as writer:
        ranked_df.to_excel(writer, sheet_name="ranked_scans", index=False)
        flagged_df.to_excel(writer, sheet_name="flagged_subset", index=False)

    print("\nSaved anomaly report to:", OUTPUT_FILE)


if __name__ == "__main__":
    main()
